### ISSUE TITLE
add dark mode

### ISSUE THREAD

**Issue by mo271** [mo271/arxiv-comments#2]
Should respect system/browser settings, i.e. detect automatically. 
Perhaps this needs coloring the share button and possibly the favicon correct, both of which currently use opacity.

**Comment by rameshkrishnan-s** [comment]
@mo271 Can you assign this issue to me??

**Comment by AviraLS22** [comment]
Shall i add a button which changes the page to its dark mode ?

**Comment by mo271** [comment]
No, I don't think we want to make this a button, but rather pick up the settings of the browser, like the page github.com does for instance.

**Comment by mo271** [comment]
fixed by #5
